db:
  port: 5433
  sslmode: disable
  host:   localhost
  username: postgres
  dbname: postgres

http:
  port: 80
  host: localhost
  MaxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

image:
  PhotoPathCat: Image/CatsPhoto/